### ISSUE TITLE
pcsx2 requires xz-utils with abi_x86_32 

### ISSUE THREAD

**Issue by sarnex** [nE0sIghT/vortex-overlay#10]
Really sorry for the bug spam.

If you have xz-utils without the USE flag abi_x86_32, pcsx2 will fail to compile. It isn't a default USE flag.

Is there a way to check for this in the pcsx2 ebuild? I had this issue and it took me too long to figure out why it wouldn't compile

Thanks as always,
sarnex

**Comment by nE0sIghT** [comment]
Thanks for testing! Should be fixed now

**Comment by sarnex** [comment]
Looks good, thanks again
