### ISSUE TITLE
s25edit-9999 ebuild

### ISSUE THREAD

**Issue by stefson** [nE0sIghT/vortex-overlay#17]
I recently found out about the s25editor, which can be found here

https://github.com/Return-To-The-Roots/s25edit 

Do you think it is possible to hack an ebuild for this? It is c++ I guess, and needs media-libs/libsdl as a compile dependency. A bit of a problem is that it lacks a makefile, but I generated a fitting one as suggested in the forum, which is attached. 

[makefile.zip](https://github.com/nE0sIghT/vortex-overlay/files/1066606/makefile.zip)

**Comment by nE0sIghT** [comment]
I can package this as separate ebuild.
I think codeblocks should have some command line switches to compile this.

**Comment by stefson** [comment]
Hey, thanks for the fast reply. Do you mean to add it as a -bin ebuild?

**Comment by nE0sIghT** [comment]
No, just add codeblocks as build dep and build it using codeblocks.

**Comment by stefson** [comment]
If you are familiar with it it might be worth a try, but I just thought about to checkout the code from github, to copy the makefile from files directory and to compile it :-)

**Comment by stefson** [comment]
s25edit is now part of the main package s25rttr
