### ISSUE TITLE
sourcing net-news/liferea fails after each sync

### ISSUE THREAD

**Issue by ghost** [nE0sIghT/vortex-overlay#2]
'''
- ERROR: net-news/liferea-1.10.14::vortex failed (depend phase):
-   error sourcing ebuild
- 
- Call stack:
-   ebuild.sh, line 584:  Called die
- The specific snippet of code:
-              source "$EBUILD" || die "error sourcing ebuild"
- 
- If you need support, post the output of `emerge --info '=net-news/liferea-1.10.14::vortex'`,
- the complete build log and the output of `emerge -pqv '=net-news/liferea-1.10.14::vortex'`.
- Working directory: '/usr/lib64/python2.7/site-packages'
- S: '/liferea-1.10.14'
  '''
  getting this after each synchronization.

**Comment by nE0sIghT** [comment]
I removed last symlinks from overlay - error must be fixed now
