### ISSUE TITLE
Maybe create libretro-overlay and share work?

### ISSUE THREAD

**Issue by dev-0x7C6** [nE0sIghT/vortex-overlay#28]
Hi,

I'm working on porting libretro cores to OE/Yocto (https://github.com/dev-0x7C6/meta-retro) which is using bitbake syntax. Bitbake recipes have similar syntax to ebuilds, it also have similar concept of classes. From what I know at early stages of development team behind OE or Yocto experimenting with portage (emerge) as their recipe parser, this maybe a reason why is so similar.

I wrote some scripts to import recipes from retropie project (https://github.com/dev-0x7C6/retropie-package-converter) and lakka (https://github.com/dev-0x7C6/lakka-package-converter). To speed my early development on recipes.

Now I have working embedded distribution (which I'm currently improving). But I don't have those libretro cores in my beloved Gentoo system installation. I'm wondering to create tool to convert recipes to ebuild format and create **libretro-overlay** and apply my tweaks from **meta-retro** and your tweaks from **vortex-overlay**. I can create this repository as independent project and make you and me as authors. Or you will be more comfortable with accepting patches to **vortex-overlay**?

What do you think? Have you time for this or we should just go with that in separate ways?

Ah and I searched your repository for libretro-core class. But I didn't found class.

Cheers,
Bartłomiej

**Comment by nE0sIghT** [comment]
Regarding libretro packages my goal is to push those ebuilds to main tree (see PR https://github.com/gentoo/gentoo/pull/13253). So one of requirements for my ebuilds is highest quality according to Gentoo's best practices.
Therefore I do not see how dedicated overlay can help to achieve this goal and I don't beleave Libretro recipes can be auto converted to high quality Gentoo's ebuilds, but I welcome any contributions that will improve the quality of libretro ebuilds.

> Ah and I searched your repository for libretro-core class. But I didn't found class.

It's in [main Gentoo tree](https://github.com/gentoo/gentoo/blob/master/eclass/libretro-core.eclass).

**Comment by dev-0x7C6** [comment]
Thanks for claryfing current situation. I was not aware that those ebuilds are being prepared to go upstream since this repository don't share common history with portage. 

> I don't beleave Libretro recipes can be auto converted to high quality Gentoo's ebuilds

For simpler cores recipes result rather trivial and class handle all of it. So for short and simple ones it easily achievable. But yeah there are more important cores that emulates modern platforms, those need more tweaking, and not all cores using makefile approach. 

> but I welcome any contributions that will improve the quality of libretro ebuilds.

You mean already existing ones, yes? With new ones I should propose them to Portage repo?

> It's in main Gentoo tree.

That's a nice surprise :-)
