### ISSUE TITLE
Cannot sync overlay - getting git pull problem

### ISSUE THREAD

**Issue by ghost** [nE0sIghT/vortex-overlay#3]
> > > Syncing repository 'vortex' into '/mnt/portage/vortex'...
> > > /usr/bin/git pull

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@gentoo-de-work.(none)')
!!! git pull error in /mnt/portage/vortex

**Comment by nE0sIghT** [comment]
Are you using plain git (not layman or portage)? If so, just set username and email as git suggests. Otherwise please post full sync log.

**Comment by ghost** [comment]
I'm using repos.conf mechanism, syncing the overlay by git. My last sync log (from main repo to the error) is - https://bpaste.net/show/b7598a03ad9d (warning: a very big wall of text :-))

**Comment by nE0sIghT** [comment]
I'm in doubt why this is happens. This can be a bug in new portage sync mechanism - please fill new request to https://bugs.gentoo.org and also please CC me.
I think you can safelly remove /mnt/portage/vortex and resync with "emain sync -r vortex" command to avoid this.

**Comment by ghost** [comment]
Removing /mnt/portage/vortex and resyncing solved the problem, thanks.
