### ISSUE TITLE
games-strategy/vcmi shortcuts do not have icons under LXQt

### ISSUE THREAD

**Issue by grepwood** [nE0sIghT/vortex-overlay#31]
Perhaps this is an error on my part? I have USE=png enabled globally. It doesn't make sense. LibreOffice is another program that stores icons in /usr/share/icons rather than /usr/share/pixmaps and it has icons in desktop shortcuts just fine.

**Comment by grepwood** [comment]
Icons arrived on next reboot.

**Comment by nE0sIghT** [comment]
There is no such issue in GNOME.  
XDG icons cache update is running also.
