### ISSUE TITLE
pcsx2 overrides compiler optimization

### ISSUE THREAD

**Issue by haarp** [nE0sIghT/vortex-overlay#4]
pcsx2 tends to override user CFLAGS with O2. Especially the GSdx needs a ton of CPU power, and it's one of the plugins that have this override in place. I'd rather compile it with -O3 or even -Ofast.

This could be fixed by having the ebuild remove -O2 from the OptimiationFlags section of the various CMakeLists.txt

**Comment by haarp** [comment]
And is there a reason you're setting -DDISABLE_ADVANCE_SIMD=TRUE ?

**Comment by nE0sIghT** [comment]
> And is there a reason you're setting -DDISABLE_ADVANCE_SIMD=TRUE

It's just historical way to strip predefined cflags.
I filter predefined by "DISABLE_ADVANCE_SIMD=TRUE" "-msse -msse2 -march=i686" flags in ebuild's prepare phase.

**Comment by haarp** [comment]
So, do you think it would be appropiate to modify the ebuild to strip the optimization flags from the build in favor of the user's CFLAGS?

**Comment by nE0sIghT** [comment]
I think it would be good idea to make it via custom-cflags use flag (user must understand that bugs in such builds must not be reported upstream)

**Comment by haarp** [comment]
agreed, that sounds reasonable

**Comment by nE0sIghT** [comment]
```
  18 Apr 2015; nE0sIghT <ykonotopov@gmail.com>
  +files/pcsx2-1.3.1-custom-cflags.patch, -pcsx2-1.3.1.ebuild,
  +pcsx2-1.3.1-r2.ebuild:
  Added custom-cflags use flag to strip default optimization flags #4

  18 Apr 2015; nE0sIghT <ykonotopov@gmail.com>
  +files/pcsx2-9999-custom-cflags.patch, metadata.xml, pcsx2-9999-r2.ebuild:
  Added custom-cflags use flag to strip default optimization flags #4
```

**Comment by haarp** [comment]
Thanks, compiles well on -Ofast :)
