### ISSUE TITLE
pcsx2: Missing dependency on gnome-base/librsvg

### ISSUE THREAD

**Issue by haarp** [nE0sIghT/vortex-overlay#6]
I only have the 64bit librsvg installed and pcsx2 can't display icons.

`Error loading theme icon 'gtk-ok' for stock: Unable to load image-loading module: /usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: cannot open shared object file: No such file or directory`

After manually emerging it with abi_x86_32, the problem disappears.

librsvg should be added as a dependency

**Comment by nE0sIghT** [comment]
That is not dependency of pcsx2 itself, but your icon theme. Which icon theme do you use?

**Comment by haarp** [comment]
A custom one, it has no ebuild.

Mhh yeah, that makes sense. The question being, how do you solve such a dependency elegantly... Difficult.

**Comment by nE0sIghT** [comment]
x11-themes/adwaita-icon-theme - default Gnome 3 icon theme - depends on librsvg, but was not converted to multilib. I can convert it and fill bug to Gentoo

**Comment by haarp** [comment]
You could, but to complete the dependency chain, pcsx2 would then have to depend on adwaita-icon-theme. I imagine a lot of people would be upset at that, and it doesn't feel like the right way.

**Comment by nE0sIghT** [comment]
Yep, i forgot that gtk+-3 support disabled now

**Comment by nE0sIghT** [comment]
Did you have svg use flag enabled on gdk-pixbuf? I think if you have it enabled, then 32bit librsvg dependency must be in graph

**Comment by haarp** [comment]
The version of gdk-pixbuf in portage doesn't have an svg useflag

**Comment by nE0sIghT** [comment]
Strange, for some reasons it was removed:
https://bugs.gentoo.org/show_bug.cgi?id=373001
https://bugs.gentoo.org/show_bug.cgi?id=363715

Anyway i can not handle that case in pcsx2 ebuild. You can fill new report at b.g.o to re-add svg use flag for gdk-pixbuf

**Comment by haarp** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=547710

**Comment by haarp** [comment]
Seems that Gentoo thinks that pcsx2 itself should depend on librsvg

**Comment by nE0sIghT** [comment]
Not really, Alexandre explained that icon theme ebuild must depends on librsvg.
https://bugs.gentoo.org/show_bug.cgi?id=547710#c3

**Comment by haarp** [comment]
Yeah, and that quite frankly makes no sense, see my reply on the bug.

**Comment by nE0sIghT** [comment]
Must be fixed in latest gtk+
