### ISSUE TITLE
wxGTK 3.0.2 reports as 3.0.1

### ISSUE THREAD

**Issue by sarnex** [nE0sIghT/vortex-overlay#9]
Hi. I'm not sure if this is a bug with your ebuild, but I have wxGTK-3.0.2.0-r3 and eselect-wxwidgets-20140423-r3 installed. When I run wx-config --version, it reports as 3.0.1. For some reason filezilla requires 3.0.2, so I can't compile filezilla.

```
sarnex@pc ~ $ wx-config --version
3.0.1
```

```
sarnex@pc ~ $ eselect wxwidgets list
Available 64bit wxWidgets profiles:
  [1]   gtk2-unicode-3.0 *
  [2]   gtk2-unicode-release-2.8
Available 32bit wxWidgets profiles:
  [1]   gtk2-unicode-3.0 *
sarnex@pc ~ $ 
```

```
sarnex@pc ~ $ equery l wxGTK
 * Searching for wxGTK ...
[I-O] [  ] x11-libs/wxGTK-2.8.12.1-r3:2.8
[I-O] [  ] x11-libs/wxGTK-3.0.2.0-r3:3.0
sarnex@pc ~ $ 

```

Any ideas?

Thanks alot,
sarnex

**Comment by nE0sIghT** [comment]
Thanks for reporting, this is fixed now. I revbumped packages
